@startuml

interface Device {
    void turnOn();
    void turnOff();

}

class Computer implements Device {
    void turnOn();
    void turnOff();

}

class TV implements Device {
    void turnOn();
    void turnOff();
    void changeChanel();
    void increaseVolume(int);
    void decreaseVolume(int);

}

class Fridge implements Device {
    void turnOn();
    void turnOff();
    Product takeProduct(Product);
    Product loadProduct(Product);

}

class LitterTray implements Device {
    void turnOn();
    void turnOff();
    void cleanPoop()

}

class TemperatureSensor implements Device {
    - int temperature;
    - List<Observer> observers
    addObserver(Observer)
    removeObserver(Observer)
    setTemperature(int temperature)
    notifyObservers()

    void turnOn();
    void turnOff();

}

abstract class DeviceFactory {
    Device createDevice();
}

class MultimediaFactory extends DeviceFactory {
    Device createDevice(): TV
    {static} MultimediaFactory getInstance()
}

class HouseholdAppliancesFactory extends DeviceFactory {
    Device createDevice(): Fridge, Computer
    {static} HouseholdAppliancesFactory getInstance()
}

class ComputerFactory extends HouseholdAppliancesFactory{
    Device createDevice(): Computer
    {static} ComputerFactory getInstance()
}

class FridgeFactory extends HouseholdAppliancesFactory{
    Device createDevice(): Fridge
    {static} FridgeFactory getInstance()
}

class HeatingFactory extends DeviceFactory {
    Device createDevice(): TemperatureSensor
    {static} HeatingFactory getInstance()
}

class HeatingSystem implements Observer{
   -int temperature
    update(int temperature)
'    if temperature is over 20 turn off heating else turn on
}

interface Observer {
    void update(int temperature)
}

interface HouseComponent {
    void displayInfo()

}

class Room implements HouseComponent {
    -List<Device> devices
    -List<Resident> residents

    void displayInfo()
    void addDevice(Device)
    void removeDevice(Device)
    void addResidence(Resident)
    void removeResident(Resident)
    List<Device> getDevices()
    List<Resident> getResidents()

}

class Floor implements HouseComponent {
    -List<Room> rooms
    void addComponent(HouseComponent component)
    void displayInfo()

}

class Building implements HouseComponent {
    -List<Floor> floors
    void addComponent(HouseComponent component)
    void displayInfo()

}

interface DeviceAction {
    void execute();
}

class TurnOnDeviceAction implements DeviceAction {
    -Device device
    TurnOnDeviceAction(device)
    void execute()
}


class TurnOffDeviceAction implements DeviceAction {
    -Device device
    TurnOffDeviceAction(device)
    void execute()
}

class LoadProductAction implements DeviceAction {
    -Device device
    -Product product;
    loadProductAction(device, product);
    void execute();
}


class TakeProductAction implements DeviceAction {
    -Device device
    -Product product;
    takeProductAction(device, product);
    void execute();
}

class IncreaseVolumeAction implements DeviceAction {
    -Device device
    -int amount
    increaseVolumeAction(device, amount)
    void execute()
}

class DecreaseVolumeAction implements DeviceAction {
    -Device device
    -int amount
    decreaseVolumeAction(device, amount)
    void execute()
}

class CleanPoopAction implements DeviceAction {
    -Device device
    CleanPoopAction(device)
    void execute()
}


class DeviceController {
    -DeviceAction action
    void setAction(DeviceAction action)
    void executeAction()
}
'
'interface Mediator {
'    void interactWithDevice(Resident resident, Device device, DeviceAction action)
'}
'
'class SmartHomeMediator implements Mediator{
'    void interactWithDevice(Resident resident, Device device, DeviceAction action)
'}


abstract class Resident {
    void interactWithDevice(Device device, DeviceAction deviceAction)
}

class Human extends Resident{
    public Human()
    void interactWithDevice(Device device, DeviceAction deviceAction)
}

class Animal extends Resident {
    public Animal()
    void interactWithDevice(Device device, DeviceAction deviceAction)

}


interface ReportVisitor {
    void visit(Building)
    void visit(Floor)
    void visit(Room)
    void visit(Device)
    void visit(Resident)
}

class HouseConfigurationReport implements ReportVisitor {
    -StringBuilder reportStringBuilder report

    void visit(Building)
    void visit(Floor)
    void visit(Room)
    void visit(Device)
    void visit(Resident)
}

class EventReport implements ReportVisitor {
    void visit(Device)
    visit(Resident)
}

class ActivityAndUsageReport implements ReportVisitor {
    void visit(Device)
    void visit(Resident)
}

class ConsumptionReport implements ReportVisitor {
    void visit(Device)
}

interface Event {
    String getType();
    String getSource();
    String getTarget();
}



Device <.. DeviceFactory
TemperatureSensor o-- Observer
DeviceController --> DeviceAction

'HouseComponent --o SmartHomeMediator
'DeviceController --o SmartHomeMediator
'Resident --o SmartHomeMediator


@enduml