@startuml

interface Observer {
    +update(temperature: int)
}

class HeatingSystem implements Observer {
    -name: String
    +update(temperature: int)
}

class Thermostat implements Observer {
    -name: String
    +update(temperature: int)
}

class TemperatureSensor {
    -observers: List<Observer>
    -temperature: int
    +addObserver(observer: Observer)
    +removeObserver(observer: Observer)
    +setTemperature(temperature: int)
    +notifyObservers()
    +turnOn()
    +turnOff()
}


TemperatureSensor o-- Observer : "notifies"

@enduml
